server:
  port: 8089
logging:
  level:
    learning: trace
spring:
  datasource:
    url:  jdbc:mysql://182.61.132.40:3306/longyt
    username: root
    password: 123123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
mybatis:
  type-aliases-package: com.longyt.develop.domain
  mapper-locations: classpath:mappers/*.xml
